### ISSUE TITLE
How do I output HTMLtags?

### ISSUE THREAD

**Issue by codymchane** [liouh/chat-bot#1]
The output is only text and the HMTL content (in the answers/responses) is rendered as plain text.

Any idea?

**Comment by liouh** [comment]
Take a look at https://github.com/liouh/chat-bot/blob/50641e11a119a530bd97e48b8bf1976a4eed769d/js/index.js#L54

I'm using jQuery's .text() to set the text content. You can change that to .html() to set innerHTML. Note that this opens up the page to cross-site scripting attacks, so be careful.

Cheers.
